// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://paonzgrjztcylndgleyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhb256Z3JqenRjeWxuZGdsZXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDE0MDgsImV4cCI6MjA2NTU3NzQwOH0.BZ4lV61Rx4BHuP57jkSlFu_iovdnOJuh1uJdSMU4hY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);